import type { PropertyDetail } from '@norde/core/properties/contracts';

/** Una ficha completa para los tests de las vistas y del JSON-LD. */
export function aPropertyDetail(overrides: Partial<PropertyDetail> = {}): PropertyDetail {
  return {
    id: '00000000-0000-7000-8000-0000000000c1',
    code: 'DEP0001',
    slug: 'departamento-3-ambientes-mataderos-dep0001',
    title: 'Departamento 3 ambientes con balcón',
    operation: 'sale',
    price: { amountCents: 9_800_000n, currency: 'USD' },
    operations: [
      { operation: 'sale', price: { amountCents: 9_800_000n, currency: 'USD' } },
      { operation: 'rent', price: null },
    ],
    propertyType: 'apartment',
    featured: true,
    expenses: { amountCents: 9_500_000n, currency: 'ARS' },
    rooms: 3,
    bedrooms: 2,
    bathrooms: 1,
    parkingSpaces: 0,
    surfaceTotalM2: 75,
    surfaceCoveredM2: 72,
    address: 'Av. Eva Perón al 5400',
    neighborhood: 'Mataderos',
    city: 'CABA',
    amenities: [],
    cover: { id: 'm1', src: '/fotos/m1/abc', width: 1600, height: 1200, description: null },
    photoCount: 2,
    description: 'Luminoso.',
    province: 'Buenos Aires',
    coordinates: null,
    toilets: null,
    ageYears: 0,
    condition: 'very_good',
    disposition: 'front',
    orientation: 'otra',
    surfaceSemiCoveredM2: null,
    surfaceLandM2: null,
    frontM: null,
    depthM: null,
    isFurnished: false,
    creditEligible: true,
    professionalUse: false,
    features: [
      { kind: 'service', name: 'Gas natural' },
      { kind: 'amenity', name: 'Pileta' },
    ],
    photos: [
      { id: 'm1', src: '/fotos/m1/abc', width: 1600, height: 1200, description: 'Living' },
      { id: 'm2', src: '/fotos/m2/abc', width: null, height: null, description: null },
    ],
    floorPlans: [],
    videoUrls: [],
    tourUrls: [],
    developmentId: null,
    updatedAt: new Date('2026-10-01T12:00:00Z'),
    ...overrides,
  };
}
